name: Publish to npm on new git tag
on:
  push:
    tags:
      - "*"
    # branches:
    #   - "**"
jobs:
  Build-Binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # node-version: "lts/*"
          node-version: 14
          registry-url: "https://registry.npmjs.org"
      - run: curl -fsSL https://deno.land/x/install/install.sh | sh
      - run: echo "DENO_INSTALL=/home/runner/.deno" >> $GITHUB_ENV
      - run: echo "$DENO_INSTALL/bin" >> $GITHUB_PATH
      - run: deno --version
      - run: npm i --no-package-lock
      - run: npm run compile
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
